sudo: required

language: generic

services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - mount_dir=$(mktemp -d)
        - docker build -t thelounge:main .
        - docker run --user "$UID" -v "${mount_dir}:/var/opt/thelounge" -d -p 9001:9000 --name main thelounge:main
        - docker exec main thelounge --version | grep --color=never -E "^v[0-9]\.[0-9]\.[0-9]" | cut -c 2- | grep -f /dev/stdin Dockerfile
        - sleep 3 # wait for the server to (hopefully) start
        - curl -sL localhost:9001 | grep "<title>The Lounge</title>"
        - stat "${mount_dir}/config.js"
    - stage: test
      script:
        - mount_dir=$(mktemp -d)
        - docker build -t thelounge:alpine -f alpine/Dockerfile alpine
        - docker run --user "$UID" -v "${mount_dir}:/var/opt/thelounge" -d -p 9002:9000 --name alpine thelounge:alpine
        - docker exec alpine thelounge --version | grep --color=never -E "^v[0-9]\.[0-9]\.[0-9]" | cut -c 2- | grep -f /dev/stdin alpine/Dockerfile
        - sleep 3 # wait for the server to (hopefully) start
        - curl -sL localhost:9002 | grep "<title>The Lounge</title>"
        - stat "${mount_dir}/config.js"
